name: null
favicon: null
layout_spectrum: 0.46703
typography_spectrum: 0.43313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: b0265f8e-3c2a-4464-8d0e-f5558e0fc1de
    url: 'My name is Tisha. '
